Version 6.5.1
## Version 6.5.1 - April 11, 2025

  - **Fixed:** Exception when you have app.UseGleamTech() in your project and when the "Referer" http header contained an invalid URL:
    ```
    System.UriFormatException: Invalid URI: The format of the URI could not be determined.
        at GleamTech.AspNet.Core.WebActivationMiddlewareExtensions...
    ```
    This was observed especially when certain pages like /Customer/Home/Forbidden or /Customer/Error/HandleError were accessed.
    This is because as the original url was invalid, it was redirected to the error pages which contained "Referer" http header
    referring to the original url with the problem.

### Included example projects:
- ASP.NET Core (C#) - Visual Studio 2019+
- ASP.NET Core on .NET Framework (C#)- Visual Studio 2017+
- ASP.NET MVC (C#) - Visual Studio 2015+
- ASP.NET MVC (VB) - Visual Studio 2015+
- ASP.NET WebForms (C#) - Visual Studio 2015+
- ASP.NET WebForms (VB) - Visual Studio 2015+